name: Sanity Tests
on: workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate .env file
        run: |
          echo "${{ secrets.PRO_ENV_FILE }}" > .env  
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
          record: true
          parallel: true 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
