name: Sanity Tests
on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "DACH_BASE_URL=${{ secrets.DACH_BASE_URL }}" >> .env
          echo "IS_PROD=${{ secrets.IS_PROD }}" >> .env
          echo "MEMBER_EMAIL_UK=${{ secrets.MEMBER_EMAIL_UK }}" >> .env
          echo "MEMBER_PASSWORD_UK=${{ secrets.MEMBER_PASSWORD_UK }}" >> .env
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
          record: true
          parallel: true 
        env:

          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
