name: Sanity Tests 2
on: 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci  

      - name: Generate .env file
        run: |
          touch .env
          echo $PRO_ENV_FILE >> .env

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          npx cypress run --spec 'cypress/tests/Sanity/' --browser chrome --record --parallel --ci-build-id $GITHUB_RUN_ID
      
      - name: Publish Mochawesome report
        if: always()
        run: |
          mkdir -p mochawesome-report
          cp -r cypress/reports/* mochawesome-report/
        continue-on-error: true
      
      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report  
