name: Sanity Tests
on: 
  workflow_dispatch:

jobs:
  Sanity-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci  

      - name: Generate .env file
        run: |
          cat > .env <<EOF
          ${{ secrets.PRO_ENV_FILE }}
          EOF

      - name: Run Sanity Tests
        uses: cypress-io/github-action@v6
        with:
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "Sanity Tests"
          spec: cypress/tests/Sanity/*
          ci-build-id: $GITHUB_RUN_ID
          config-file: cypress.config.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
