name: Sanity Tests New
on: 
  workflow_dispatch:

jobs:
  Sanity-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci  

      - name: Generate .env file
        run: |
          cat > .env <<EOF
          ${{ secrets.PRO_ENV_FILE }}
          EOF

      - name: Run Sanity Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          parallel: true
          group: "Sanity Tests"
          spec: cypress/tests/Sanity/*
          config-file: cypress.config.ts
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CI: true
