name: Sanity Tests
on: 
  workflow_dispatch:

jobs:
  Sanity-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2, 3, 4, 5, 6, 7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run:  npm install

      - name: Generate .env file
        run: |
          cat > .env <<EOF
          ${{ secrets.PRO_ENV_FILE }}
          EOF

      - name: Cleanup reports
        run:  npm run clean-reports

      - name: Run Tests
        run:  npx cypress run --config-file ci-cypress.config.ts --spec $(node sanity-parallel.ts ${{ matrix.containers }} 8) --browser chrome
      
      - name: Upload Cypress Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports-${{ matrix.containers }}
          path: cypress/reports/

  merge-reports:
    needs: Sanity-Tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Cypress Report 0
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-0
          path: cypress/reports/cypress-reports-0

      - name: Download Cypress Report 1
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-1
          path: cypress/reports/cypress-reports-1

      - name: Download Cypress Report 2
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-2
          path: cypress/reports/cypress-reports-2

      - name: Download Cypress Report 3
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-3
          path: cypress/reports/cypress-reports-3

      - name: Download Cypress Report 4
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-4
          path: cypress/reports/cypress-reports-4

      - name: Download Cypress Report 5
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-5
          path: cypress/reports/cypress-reports-5

      - name: Download Cypress Report 6
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-6
          path: cypress/reports/cypress-reports-6

      - name: Download Cypress Report 7
        uses: actions/download-artifact@v4
        with:
          name: cypress-reports-7
          path: cypress/reports/cypress-reports-7  

      - name: Collect Cypress Intermediate Reports
        run: |
          mkdir -p cypress/reports/all
          for i in {0..7}; do
            rsync -av --ignore-existing cypress/reports/cypress-reports-$i/* cypress/reports/all/
          done

      - name: Install Packages
        run:  npm install --save-dev mochawesome-merge marge cypress-multi-reporters    

      - name: Merge Cypress Reports
        run: |
          npm run final_report
          echo "DATE=$(date +'%d-%B-%Y')" >> $GITHUB_ENV

      - name: Cleanup Intermediate Reports
        run: rm -rf cypress/reports/all/*.json

      # Deleting Intermediate Reports Artifacts
      - uses: geekyeggo/delete-artifact@v5
        if: always()
        with:
          failOnError: false
          name: |
              cypress-reports-0
              cypress-reports-1
              cypress-reports-2
              cypress-reports-3
              cypress-reports-4
              cypress-reports-5
              cypress-reports-6
              cypress-reports-7

      - name: Upload Cypress Merged Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Sanity-Test-Report-${{ env.DATE }}
          path: cypress/reports/all/
