name: Sanity Tests 2
on: 
  workflow_dispatch:

jobs:
  Sanity-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run:  npm install

      - name: Generate .env file
        run: |
          cat > .env <<EOF
          ${{ secrets.PRO_ENV_FILE }}
          EOF  

      - name: Run Tests
        run:  npx cypress run --config-file ci-cypress.config.ts  --env allure=true --spec $(node sanity-parallel.ts ${{ matrix.containers }} 8) --browser chrome
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: ReportsData
          path: allure-results
  Reports:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: Sanity-Tests
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ReportsData
          path: allure-results 
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
            ref: gh-pages
            path: gh-pages
         
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
  
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
